# Generated by Django 5.0.4 on 2024-04-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='GrandOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grand_total', models.IntegerField()),
                ('table_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('orders', models.ManyToManyField(to='menu.orderdetail')),
            ],
        ),
    ]
