# Generated by Django 5.0.4 on 2024-04-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_orderdetail_grandorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandorder',
            name='grand_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
