# Generated by Django 5.0.4 on 2024-04-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_grandorder_grand_total_alter_orderdetail_sum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='sum',
            new_name='total_price',
        ),
    ]
